version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-dev
    ports:
      - "8088:8088"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./argus:/var/www/html:ro  # Mount source code as read-only for nginx
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: php-fpm
    volumes:
      - ./argus:/var/www/html  # Mount source code for live editing
      - ./argus/vendor:/var/www/html/vendor  # Persist vendor directory
      - ./logs:/var/log  # Mount logs directory for easier access
    networks:
      - app-network
    # Restart policy for development
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data_dev:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/backups:/backups  # Mount backup directory
    networks:
      - app-network

  # Optional: phpMyAdmin for development
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-dev
    ports:
      - "8089:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - app-network
    profiles:
      - tools  # Use with: docker-compose --profile tools up

volumes:
  mariadb_data_dev:
  php_vendor:  # Persist vendor directory to avoid reinstalling on restart

networks:
  app-network:
    driver: bridge